### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by trashbirdecology** [cbahlai/monarch_regime#4]
You know, if you want to.

**Comment by cbahlai** [comment]
*FACEPALM*

I can't believe I forgot to do this. Thanks @TrashBirdEcology - it's a CC-BY 4.0 now :)

**Comment by trashbirdecology** [comment]
Can I ask why you use this license?


Jessica L. Burnett, M.Sc.
Ph.D. Candidate
Nebraska Cooperative Fish & Wildlife Research Unit
<http://snr.unl.edu/necoopunit/>
School of Natural Resources
University of Nebraska-Lincoln
+1.352.792.5425

<http://snr.unl.edu/necoopunit/>

**Comment by cbahlai** [comment]
Sure you can!
1) It's the one I usually use,  and is well documented so I don't have to think too hard about it
2) it's the one most aligned with typical academic citation standards, and given this work is centered on an academic pub, it's an easy sell to more OA-hesitant collaborators 
3) in this particular repo, I've used some images on some figures that are under a CC-BY 3.0, so that's close enough that I don't have to worry about fiddly license stacking problems!

**Comment by trashbirdecology** [comment]
Thanks!

I have been using the MIT license and was curious why you choose that one.




Jessica L. Burnett, M.Sc.
Ph.D. Candidate
Nebraska Cooperative Fish & Wildlife Research Unit
<http://snr.unl.edu/necoopunit/>
School of Natural Resources
University of Nebraska-Lincoln
+1.352.792.5425

<http://snr.unl.edu/necoopunit/>
